# yml  yaml
# Yet Another Markup Language

spring:
  rabbitmq:
    host: 192.168.64.3
    port: 5672
    username: admin
    password: admin
  application:
    name: item-service
  cloud:
    config:
      override-none: true   
server:
  port: 8001

eureka:
  client:
    service-url:
      # 默认地点, 要由公共云服务来提供
      # 如果是私有服务器, 必须写 defaultZone
      defaultZone: http://eureka1:2001/eureka
      
      
